language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm
    - hhvm-nightly

matrix:
    allow_failures:
        - php: hhvm-nightly
    fast_finish: true

before_script:
  - composer install --prefer-source

script: ./vendor/bin/phpunit --coverage-text

notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/00155326ac830607d29d
    on_success: always
    on_failure: always
    on_start: false
